{% set version = "0.20.0" %}
{% set cov_fail_under = 90 %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
    sha256: 02167522c4dc759f91c4ab19854639cd1e9f6e0abfca75e119682b541d1bd63f
  - folder: src
    url: https://github.com/pytest-dev/pytest-xprocess/archive/refs/tags/{{ version }}.tar.gz
    sha256: ea21a6476b28a6ddca8e6a4e502c783f379b6b9d5901fe4e227801d6e9b7e76b

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - psutil
    - pytest >=2.8
    - python >=3.7

test:
  source_files:
    - src/tests
  requires:
    - pip
    - coverage
  imports:
    - xprocess
  commands:
    - pip check
    - coverage run -m pytest -v src/tests
    - coverage report --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: A pytest plugin for managing processes across test runs.
  license: MIT
  license_file: dist/LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
