{% set version = "0.22.2" %}
{% set cov_fail_under = 90 %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
    sha256: 599ee25b938e8f259e18d9c5b4d6384884f8a6a28ca51eed32d0d9526bdcf77c
  - folder: src
    url: https://github.com/pytest-dev/pytest-xprocess/archive/refs/tags/{{ version }}.tar.gz
    sha256: 407fd6343682a87925c1e9b690e36c963a648da50a4c7d7dd70a2ba2639f59bf

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - psutil
    - py
    - pytest >=2.8
    - python >=3.7

test:
  source_files:
    - src/tests
  requires:
    - pip
    - coverage
  imports:
    - xprocess
  commands:
    - pip check
    - coverage run -m pytest -v src/tests
    - coverage report --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: A pytest plugin for managing processes across test runs.
  license: MIT
  license_file: dist/LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
