{% set version = "0.23.0" %}
{% set cov_fail_under = 90 %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
    sha256: f8d4041a20a1c1ef1943054e4a3df7ac7b43e7f291f640f43c34e9dcc4b34dfa
  - folder: src
    url: https://github.com/pytest-dev/pytest-xprocess/archive/refs/tags/{{ version }}.tar.gz
    sha256: 51ff2e917f4716ac67c108ffcd4bd805a09de8a5b5bccf268565a0819b02169d

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - psutil
    - pytest >=2.8
    - python >=3.8

test:
  source_files:
    - src/tests
  requires:
    - pip
    - coverage
  imports:
    - xprocess
  commands:
    - pip check
    - coverage run -m pytest -v src/tests
    - coverage report --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: A pytest plugin for managing processes across test runs.
  license: MIT
  license_file: dist/LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
