{% set version = "1.0.2" %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
  sha256: 15e270637586eabc56755ee5fcc81c48bdb46ba7ef7c0d5b1b64302d080cc60f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm >=6.2.3
    - wheel
  run:
    - psutil
    - pytest >=2.8
    - python

test:
  source_files:
    - tests
  requires:
    - coverage
    - pip
    - python
    - pytest
  imports:
    - xprocess
  commands:
    - pip check
    - coverage run --source xprocess --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=87
    - pytest -vv tests

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: pytest external process plugin 
  description: |
      A pytest plugin for managing external processes across test runs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io
  dev_url: https://github.com/pytest-dev/pytest-xprocess

extra:
  recipe-maintainers:
    - bollwyvl
