{% set version = "1.0.0" %}
{% set cov_fail_under = 99 %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
    sha256: 40944d0da8152224752ebc87c91187207db2c96e50ebe895f6ad5a7c1c44624a
  - folder: src
    url: https://github.com/pytest-dev/pytest-xprocess/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 013617f6a31587179c0e8b1848562a859292cc8f0b506aa7a0ed9fa7e498ccab

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm >=6.2.3
  run:
    - psutil
    - pytest >=2.8
    - python >=3.9

test:
  source_files:
    - src/tests
  requires:
    - pip
    - coverage
  imports:
    - xprocess
  commands:
    - pip check
    - coverage run -m pytest -v src/tests
    - coverage report --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: A pytest plugin for managing processes across test runs.
  license: MIT
  license_file: dist/LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
