{% set version = "0.19.0" %}
{% set cov_fail_under = 90 %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
  sha256: 1820c549d671edb2c89c25ff1e38c70ecda0fefe280f13c45a2c8c6d66d7b50e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools-scm
  run:
    - psutil
    - pytest >=2.8
    - python >=3.5

test:
  source_files:
    - tests
  requires:
    - pip
    - coverage
  imports:
    - pytest_xprocess
    - xprocess
  commands:
    - pip check
    - coverage run -m pytest -v
    - coverage report --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: A pytest plugin for managing processes across test runs.
  license: MIT
  license_file: LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
