{% set version = "0.21.0" %}
{% set cov_fail_under = 90 %}

package:
  name: pytest-xprocess
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pytest-xprocess/pytest-xprocess-{{ version }}.tar.gz
    sha256: f9470bfcf884f7299eb6b82a43d298c318b8e53ec314ee624c987e0e87c1b449
  - folder: src
    url: https://github.com/pytest-dev/pytest-xprocess/archive/refs/tags/{{ version }}.tar.gz
    sha256: 7444a34c92fa001db114f4af5b4376c99c7ce1b39bc877209635a08f1989bb0e

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - psutil
    - pytest >=2.8
    - python >=3.7

test:
  source_files:
    - src/tests
  requires:
    - pip
    - coverage
  imports:
    - xprocess
  commands:
    - pip check
    - coverage run -m pytest -v src/tests
    - coverage report --fail-under={{ cov_fail_under }}

about:
  home: https://github.com/pytest-dev/pytest-xprocess
  summary: A pytest plugin for managing processes across test runs.
  license: MIT
  license_file: dist/LICENSE
  doc_url: https://pytest-xprocess.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
